import { Award, LayoutGrid, Star, Timer, Tv, Globe as GlobeIcon, Layers, Sparkles } from 'lucide-react'

/** Fallback local; precios/límites se sobrescriben desde el catálogo SaaS. */
export const plansDataBase = {
  sigdef: {
    title: 'Solo SIGDEF (Gestión)',
    subtitle: 'Módulo Administrativo y Padrón Federativo',
    color: '#10b981',
    cardClass: '',
    checkClass: 'icon-check-green',
    btnFeaturedClass: 'btn-acc-green',
    btnOutlineClass: 'btn-acc-outline',
    tiers: [
      {
        id: 'sigdef-s',
        name: 'Plan Esencial',
        limit: 'Hasta 200 atletas activos',
        price: '$50',
        period: '/mes',
        annualPrice: 'Anual: $480/año (~$40/mes)',
        featured: false,
        icon: LayoutGrid,
        color: '#10b981',
        features: [
          'Panel Admin Federación (sin dashboard Club)',
          'Padrón digital y categorización por edad',
          'Legajo de datos personales',
          'Validación documental básica (PDF)',
          'Tutoría legal para menores',
          'Exportación PDF de planillas',
          'Sin carga de imágenes',
        ],
      },
      {
        id: 'sigdef-m',
        name: 'Plan Profesional',
        limit: 'Hasta 400 atletas activos',
        price: '$120',
        period: '/mes',
        annualPrice: 'Anual: $1,150/año (~$96/mes)',
        featured: true,
        icon: Award,
        color: '#10b981',
        features: [
          'Todo lo del Plan Esencial',
          'Dashboard Federación + Club',
          'Carga descentralizada desde clubes',
          'Flujo de aprobación remota',
          'Matrícula y control de afiliación',
          'Filtros por club, pago y vigencia',
          'Sin carga de imágenes',
        ],
      },
      {
        id: 'sigdef-l',
        name: 'Plan Ecosistema',
        limit: 'Atletas ilimitados',
        price: '$250',
        period: '/mes',
        annualPrice: 'Anual: $2,400/año (~$200/mes)',
        featured: false,
        icon: Star,
        color: '#10b981',
        features: [
          'Todo lo del Plan Profesional',
          'Carga de imágenes en legajos',
          'Mensajería Federación–Clubes',
          'Notificaciones masivas',
          'Auditoría de logs',
          'Resoluciones digitales',
          'Soporte prioritario',
        ],
      },
    ],
  },
  sporttrack: {
    title: 'Solo SportTrack (Eventos)',
    subtitle: 'Módulo de Competencias, Tiempos y Resultados',
    color: '#0070f3',
    cardClass: 'st-theme',
    checkClass: 'icon-check-blue',
    btnFeaturedClass: 'btn-acc-blue',
    btnOutlineClass: 'btn-acc-outline btn-acc-outline-blue',
    tiers: [
      {
        id: 'st-s',
        name: 'Plan Esencial',
        limit: 'Hasta 200 atletas activos',
        price: '$40',
        period: '/mes',
        annualPrice: 'Anual: $380/año (~$31/mes)',
        featured: false,
        icon: Timer,
        color: '#0070f3',
        features: [
          'Schedule e inscripción a regatas',
          'Carga manual de tiempos y DQ',
          'Pizarra pública (actualización por polling)',
          'Planillas y series',
          'Exportación PDF de resultados',
          'Sin Live SignalR',
          'Sin consolas de juez',
        ],
      },
      {
        id: 'st-m',
        name: 'Plan Profesional',
        limit: 'Hasta 400 atletas activos',
        price: '$90',
        period: '/mes',
        annualPrice: 'Anual: $860/año (~$71/mes)',
        featured: true,
        icon: Tv,
        color: '#0070f3',
        features: [
          'Todo lo del Plan Esencial',
          'Resultados Live en tiempo real (SignalR)',
          'Penalidades y descalificaciones',
          'Cronograma interactivo',
          'Filtros por series y categorías',
          'Sin consolas de juez',
          'PDF de regatas',
        ],
      },
      {
        id: 'st-l',
        name: 'Plan Ecosistema',
        limit: 'Atletas ilimitados',
        price: '$190',
        period: '/mes',
        annualPrice: 'Anual: $1,800/año (~$150/mes)',
        featured: false,
        icon: GlobeIcon,
        color: '#0070f3',
        features: [
          'Todo lo del Plan Profesional',
          'Consolas Largador / Cronometrista / Control',
          'Live SignalR completo',
          'Carga manual + jueces',
          'Soporte prioritario',
          'Exportación PDF avanzada',
          'Panel admin completo',
        ],
      },
    ],
  },
  duo: {
    title: 'Pack Dúo (Ecosistema)',
    subtitle: 'SIGDEF + SportTrack Integrados (Ahorro del 20%)',
    color: '#3daa94',
    cardClass: 'duo-theme',
    checkClass: 'icon-check-green',
    btnFeaturedClass: 'btn-acc-green',
    btnOutlineClass: 'btn-acc-outline',
    tiers: [
      {
        id: 'duo-s',
        name: 'Plan Esencial',
        limit: 'Hasta 200 atletas activos',
        price: '$75',
        period: '/mes',
        annualPrice: 'Anual: $720/año (~$60/mes)',
        featured: false,
        icon: Layers,
        color: '#3daa94',
        features: [
          'SIGDEF Esencial + SportTrack Esencial',
          'Sincronización básica padrón ↔ regatas',
          'Carga manual de tiempos',
          'Pizarra pública (polling)',
          'PDF en ambos módulos',
          'Sin dashboard Club / sin jueces / sin Live',
          'Soporte por email',
        ],
      },
      {
        id: 'duo-m',
        name: 'Plan Profesional',
        limit: 'Hasta 400 atletas activos',
        price: '$170',
        period: '/mes',
        annualPrice: 'Anual: $1,600/año (~$133/mes)',
        featured: true,
        icon: Sparkles,
        color: '#3daa94',
        features: [
          'SIGDEF Profesional + SportTrack Profesional',
          'Dashboard Club + aprobación remota',
          'Live SignalR de resultados',
          'Inscripción descentralizada',
          'Sin consolas de juez',
          'Sin carga de imágenes',
          'Setup e inducción incluidos',
        ],
      },
      {
        id: 'duo-l',
        name: 'Plan Ecosistema',
        limit: 'Atletas ilimitados',
        price: '$350',
        period: '/mes',
        annualPrice: 'Anual: $3,360/año (~$280/mes)',
        featured: false,
        icon: Star,
        color: '#3daa94',
        features: [
          'SIGDEF Ecosistema + SportTrack Ecosistema',
          'Jueces + Live + Club + imágenes',
          'Todo el stack unificado',
          'Mensajería y notificaciones',
          'Soporte prioritario',
          'Atletas ilimitados',
          'Máxima integración',
        ],
      },
    ],
  },
}
